### ISSUE TITLE
Incorrect random sampling in cross-dataset InstaHide

### ISSUE THREAD

**Issue by carlini** [Hazelsuko07/InstaHide#3]
The updated arXiv version of InstaHide says that it is important to "Set a conservative upper threshold for the coefficients in mixing". The cross-dataset code implements this constraint incorrectly.

It checks first that the upper bound is valid (and if not, re-samples the randomness) and *then* that the lower bound is valid (and if not, re-samples). If the lower-bound is ever incorrect, then after-resampling the upper bound check is not enforced.

A correct implementation should enforce both constraints simultaneously.

https://github.com/Hazelsuko07/InstaHide/blob/8048b06a51d745982806a09fb46aca0b063dd3cb/train_cross.py#L124-L130

**Comment by Hazelsuko07** [comment]
Thanks for catching that! You are right about this. 

Just fixed in 26fa3b20340d86f5db0b76ffb0fe077ea966e152

**Comment by carlini** [comment]
The change looks good. The only thing I can think of is that the prior code tested `if args.dom > 0:` but the new code removes this test, so if ever `args.dom==0` then it will never proceed.

**Comment by Hazelsuko07** [comment]
Thanks! But I am not sure if `args.dom==0` will cause a problem. 

The new test starts at line 125:
https://github.com/Hazelsuko07/InstaHide/blob/26fa3b20340d86f5db0b76ffb0fe077ea966e152/train_cross.py#L122-L126

If `args.dom==0`, then the right part of the test will never be true, since line 122 enforces all lam[i][*]'s to be non-negative. In that case, the code is equivalent to just doing an upper bound test.

Also tried to run the code by setting `--dom 0`, and it worked out fine.

Please let me know if I missed something.
